name: PR Checklist Validator (it will popp when developer raises PR)

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check unchecked boxes
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";

            if (body.includes("- [ ]")) {
              core.setFailed("❌ Please complete all checklist items before merging.");
            } else {
              console.log("✅ All checklist items are checked.");
            }
