name: Deploy Frontend via ECR + SSM

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "632718277269"
  ECR_REPO: "dev/own-tenant-portal"
  IMAGE_NAME: "632718277269.dkr.ecr.ap-south-1.amazonaws.com/dev/own-tenant-portal"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v4


      # AWS Login
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::632718277269:role/sonaliJ-oidc-github-role
          aws-region: ${{ env.AWS_REGION }}


      # Login to ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com


      # Set Image Tag
      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV


      # Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # Build & Push
      - name: Build & Push to ECR
        working-directory: application-code/web-tier
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -t $IMAGE_NAME:latest \
            --push .


      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-040d03f0caf9ea982 \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Frontend (ECR Fixed)" \
            --parameters commands='[
              "set -e",
      
              "sudo dnf install -y docker awscli jq",
      
              "sudo systemctl start docker",
              "sudo systemctl enable docker",
      
              "export AWS_REGION=ap-south-1",
      
              "export PATH=$PATH:/usr/local/bin:/usr/bin",
      
              "/usr/bin/aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 632718277269.dkr.ecr.ap-south-1.amazonaws.com",
      
              "sudo docker pull 632718277269.dkr.ecr.ap-south-1.amazonaws.com/dev/own-tenant-portal:latest",
      
              "sudo docker stop web || true",
              "sudo docker rm web || true",
      
              "sudo docker run -d --name web -p 80:80 --restart always 632718277269.dkr.ecr.ap-south-1.amazonaws.com/dev/own-tenant-portal:latest",
      
              "sudo docker ps"
            ]'
