name: Deploy Frontend Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v4


      # Enable Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # AWS Login
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::632718277269:role/sonaliJ-oidc-github-role
          aws-region: ap-south-1


      - name: Check Identity
        run: aws sts get-caller-identity


      # DockerHub Creds
      - name: Fetch Docker creds
        run: |
          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id dockerhub/credentials \
            --query SecretString \
            --output text)

          echo "DOCKER_USERNAME=$(echo $SECRET | jq -r '.DOCKER_USERNAME')" >> $GITHUB_ENV
          echo "DOCKER_TOKEN=$(echo $SECRET | jq -r '.DOCKER_TOKEN')" >> $GITHUB_ENV


      # Docker Login
      - name: Docker Login
        run: |
          echo "$DOCKER_TOKEN" | docker login \
            -u "$DOCKER_USERNAME" \
            --password-stdin


      # Tag
      - name: Set image tag
        run: echo "NEW_TAG=$(date +%s)" >> $GITHUB_ENV


      ########################
      # BUILD + PUSH (ARM)
      ########################
      - name: Build & Push Frontend (Multi-Arch)
        working-directory: application-code/web-tier
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $DOCKER_USERNAME/frontend:${NEW_TAG} \
            -t $DOCKER_USERNAME/frontend:latest \
            --push .


      ########################
      # DEPLOY FRONTEND
      ########################
      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-06fe393f7e5a98224 \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Frontend Only" \
            --parameters commands='[
              "set -e",

              "sudo dnf install -y docker || true",
              "sudo systemctl start docker",

              "SECRET=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query SecretString --output text)",

              "U=$(echo $SECRET | jq -r .DOCKER_USERNAME)",
              "T=$(echo $SECRET | jq -r .DOCKER_TOKEN)",

              "echo $T | docker login -u $U --password-stdin",

              "docker pull $U/frontend:latest",

              "docker stop web || true",
              "docker rm web || true",

              "docker run -d --name web -p 80:80 --restart always $U/frontend:latest"
            ]'
