name: Publish Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ---- FETCH TAGS FOR SEMVER ----
      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine Semantic Version
        id: semver
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          MAJOR=$(echo $LAST_TAG | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d. -f2)
          PATCH=$(echo $LAST_TAG | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "new_tag=$NEW_TAG"

      # ---- DOCKER LOGIN ----
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- BUILD & PUSH BACKEND DOCKER IMAGE (app-tier) ----
      - name: Build Backend Docker Image
        working-directory: application-code/app-tier
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ env.NE_

